---

name: testing
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'
        target:
          - default
          - follow

    name: "[${{ matrix.version}}] ${{ matrix.target }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Test
        run: |
          make _test FILE=${target}.sh VERSION=${version}
        env:
          target: ${{ matrix.target }}
          version: ${{ matrix.version }}
