---

###
### Lints all generic and json files in the whole git repository
###

name: building
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - '2.7'
          - '3.6'
          - '3.7'
          - '3.8'
        target:
          - build
          - dist

    name: "[ ${{ matrix.target }} ${{ matrix.version}} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build
        run: |
          make ${target} VERSION=${version}
        env:
          target: ${{ matrix.target }}
          version: ${{ matrix.version }}
